# -*- coding: utf-8 -*-
"""Fixture tests for the decision logic inside .github/workflows/pr-automerge.yml.

WHY THIS IS IN THE GATE
-----------------------
`pr-automerge.yml` merges generated PRs to master unattended, and master auto-deploys to
Vercel. Its two Python blocks are therefore the last thing standing between a bot commit and
the live site, and a workflow cannot be unit-tested by running it — you only find out in
production. So this extracts both blocks from the YAML and runs them against fixtures.

The two questions worth protecting, because getting either wrong is silent rather than loud:

  1. WHO is eligible. Generated PRs come from two different authors: data/deck refreshes are
     `app/github-actions`, while the autonomous loop's PRs run under the OWNER's own account
     and are separated from hand-written ones only by a "Generated by [Claude Code]" marker.
     Widening this by accident auto-merges the owner's own work.

  2. Whether the gate really passed ON THE CURRENT HEAD. `cancelled` and `action_required`
     mean the gate never ran, and both are routine here (qa.yml sets cancel-in-progress; bot
     PRs land on action_required). Reading either as a verdict is the bug: as "green" it
     merges ungated code, as "red" it wedges the PR forever.

  3. That ONE unmergeable PR cannot block the ones behind it. The queue is drained oldest-first,
     so if a red (or ungated, or still-running) PR at the head stopped the scan, every PR behind
     it would wait for as long as that one stayed open — which for a red bot PR is indefinitely.
     The decision block must skip past it and keep looking.

Deliberately does NOT import yaml — the gate's interpreter is not guaranteed to have it, and
the blocks are extracted from the raw text with the same indentation rules YAML would apply.
"""
import json
import os
import re
import subprocess
import sys
import tempfile
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
WF = os.path.join(REPO, ".github", "workflows", "pr-automerge.yml")


def _dedent_block(raw):
    """YAML `run: |` strips the block's common indentation before the shell sees it."""
    return textwrap.dedent(raw)


def extract():
    src = open(WF, encoding="utf-8").read()
    m = re.search(r"[ \t]*python3 - <<'PY'[^\n]*\n(.*?)\n[ \t]*PY\b", src, re.S)
    if not m:
        raise SystemExit("FAIL: could not find the eligibility block in %s" % WF)
    m2 = re.search(r'[ \t]*DECIDE=\$\(python3 -c "\n(.*?)\n[ \t]*"\)', src, re.S)
    if not m2:
        raise SystemExit("FAIL: could not find the decision block in %s" % WF)
    return _dedent_block(m.group(1)), _dedent_block(m2.group(1))


PICK_SRC, DECIDE_SRC = extract()
compile(PICK_SRC, "pick", "exec")
compile(DECIDE_SRC, "decide", "exec")

TMP = tempfile.mkdtemp()


def run_pick(prs, owner="kaustavb2101"):
    """Returns stdout (annotations) + the $GITHUB_OUTPUT the block wrote, concatenated.

    The block writes its step outputs to $GITHUB_OUTPUT and its ::notice:: lines to stdout, and
    keeping them apart is load-bearing: redirecting both into $GITHUB_OUTPUT is what made the
    runner reject the file with "Invalid format" and fail the step.
    """
    p = os.path.join(TMP, "prs.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(prs, f)
    gho = os.path.join(TMP, "gh_output")
    open(gho, "w").close()
    src = PICK_SRC.replace('"/tmp/prs.json"', json.dumps(p))
    env = dict(os.environ, OWNER=owner, GITHUB_OUTPUT=gho)
    r = subprocess.run([sys.executable, "-c", src], capture_output=True, text=True, env=env)
    written = open(gho, encoding="utf-8").read()
    # A step output line may never contain a newline mid-value, and `candidates` is JSON built by
    # hand — if it ever wrapped, the runner would silently truncate the candidate list.
    for line in written.splitlines():
        assert "=" in line, "malformed $GITHUB_OUTPUT line: %r" % line
    return r.stdout + written + r.stderr


def run_decide(runs, cands):
    """Returns (decision_line, all_output) — the decision is the LAST line, as bash reads it."""
    p = os.path.join(TMP, "runs.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(runs, f)
    src = DECIDE_SRC.replace("'/tmp/runs.json'", json.dumps(p))
    env = dict(os.environ, CANDS=json.dumps(cands))
    r = subprocess.run([sys.executable, "-c", src], capture_output=True, text=True, env=env)
    out = r.stdout.strip() or r.stderr.strip()
    return (out.splitlines()[-1] if out else ""), out


def cand(n, sha, draft=False):
    return {"number": n, "branch": "b%d" % n, "sha": sha, "draft": draft}


def qa(sha, status="completed", conclusion="success"):
    return {"headSha": sha, "status": status, "conclusion": conclusion}


def pr(n, login, body="", draft=False, state="CLEAN", created="2026-08-01",
       owner="kaustavb2101", is_bot=None):
    """`is_bot` defaults to what gh actually reports: true for any 'app/...' login.

    This helper previously hard-coded login="github-actions" with no is_bot field, which is NOT
    what the API returns and is why the suite passed while the workflow merged nothing in
    production. Fixtures must use the real shape.
    """
    if is_bot is None:
        is_bot = login.startswith("app/")
    return {"number": n, "author": {"login": login, "is_bot": is_bot}, "isDraft": draft,
            "headRefName": "b%d" % n, "headRefOid": "a" * 40, "body": body,
            "createdAt": created, "mergeable": "MERGEABLE", "mergeStateStatus": state,
            "headRepositoryOwner": {"login": owner}}


SHA = "a" * 40
FAILED = []


def check(name, got, expect, contains=False):
    good = (expect in got) if contains else (got == expect)
    if not good:
        FAILED.append("%s\n      expected %r, got %r" % (name, expect, got))
    return good


ELIGIBILITY = [
    # THE REGRESSION THAT MATTERED. `gh pr list --json author` reports the App as
    # "app/github-actions" with is_bot=true. Matching only the un-prefixed spellings made the job
    # call every bot PR hand-written and merge nothing, silently, while appearing to work — and the
    # suite passed anyway because these fixtures used a login the API never returns.
    ("REAL gh shape: app/github-actions is eligible",
     [pr(1, "app/github-actions")], "found=yes"),
    ("REAL gh shape: is_bot alone is enough, whatever the login",
     [pr(1, "app/some-other-bot", is_bot=True)], "found=yes"),
    ("actions bot, un-prefixed login still accepted",
     [pr(1, "github-actions", is_bot=False)], "found=yes"),
    ("actions bot, bracketed login", [pr(1, "github-actions[bot]", is_bot=False)], "found=yes"),
    ("hand-written owner PR is left alone",
     [pr(2, "kaustavb2101", body="just a fix")], "found=none"),
    ("loop PR carrying the Claude marker is eligible",
     [pr(3, "kaustavb2101", body="_Generated by [Claude Code](https://x)_")], "found=yes"),
    ("'Generated with' phrasing also matches",
     [pr(4, "kaustavb2101", body="Generated with [Claude Code](https://x)")], "found=yes"),
    ("null body does not crash the marker test",
     [{**pr(14, "kaustavb2101"), "body": None}], "found=none"),
    ("DIRTY is left to pr-autoresolve",
     [pr(5, "github-actions", state="DIRTY")], "found=none"),
    ("UNKNOWN mergeability waits for GitHub to finish computing",
     [pr(6, "github-actions", state="UNKNOWN")], "found=none"),
    ("a fork is never merged", [pr(7, "github-actions", owner="someone-else")], "found=none"),
    ("oldest eligible PR is offered first",
     [pr(8, "github-actions", created="2026-08-09"),
      pr(9, "github-actions", created="2026-08-02")], '"number":9,'),
    ("every eligible PR is offered, not just the first",
     [pr(8, "github-actions", created="2026-08-09"),
      pr(9, "github-actions", created="2026-08-02")], '"number":8,'),
    # The deadlock guard: pr-autoresolve skips drafts and this job skips DIRTY, so a PR that is
    # both would be touched by neither and sit wedged forever. It must still be promoted.
    ("draft+DIRTY is promoted even though it cannot merge",
     [pr(10, "github-actions", draft=True, state="DIRTY")], "promote=10"),
    ("draft+DIRTY is still not merged",
     [pr(11, "github-actions", draft=True, state="DIRTY")], "found=none"),
    ("draft+CLEAN is both promoted and merged",
     [pr(12, "github-actions", draft=True, state="CLEAN")], "found=yes"),
    ("a hand-written draft is NOT promoted",
     [pr(13, "kaustavb2101", draft=True, body="mine")], "promote="),
    ("a real bot draft IS promoted",
     [pr(15, "app/github-actions", draft=True)], "promote=15"),
]

# (name, prs, substring that must NOT appear anywhere in the output)
NEVER = [
    ("a real bot PR is never reported as hand-written",
     [pr(1, "app/github-actions")], "hand-written"),
    ("a real bot draft PR is never reported as hand-written",
     [pr(2, "app/github-actions", draft=True)], "hand-written"),
    # $GITHUB_OUTPUT must carry ONLY key=value lines. Annotations going in there is what made the
    # runner reject the file outright with "Invalid format" and fail the step.
    ("annotations never land in the step outputs",
     [pr(3, "kaustavb2101", body="mine")], "::notice::found"),
]

A, B, C = "a" * 40, "b" * 40, "c" * 40

# (name, qa runs, candidates, expected decision line)
DECISIONS = [
    ("success on this head merges it",
     [qa(A)], [cand(1, A)], "merge|1|b1|%s|false" % A),
    ("success on a DIFFERENT head does not count (the stale-green trap)",
     [qa(B)], [cand(1, A)], "dispatch|1|b1||"),
    ("cancelled means the gate never ran, not that it failed",
     [qa(A, conclusion="cancelled")], [cand(1, A)], "dispatch|1|b1||"),
    ("action_required means the gate never ran either",
     [qa(A, conclusion="action_required")], [cand(1, A)], "dispatch|1|b1||"),
    ("a run still going is left alone, and NOT re-dispatched onto itself",
     [qa(A, status="in_progress", conclusion=None)], [cand(1, A)], "none|||"),
    ("a real failure is not merged",
     [qa(A, conclusion="failure")], [cand(1, A)], "none|||"),
    ("timed_out is not merged",
     [qa(A, conclusion="timed_out")], [cand(1, A)], "none|||"),
    ("an earlier failure is superseded by a later success",
     [qa(A, conclusion="failure"), qa(A)], [cand(1, A)], "merge|1|b1|%s|false" % A),
    ("a queued run alongside a cancelled one waits (never re-dispatch onto ourselves)",
     [qa(A, conclusion="cancelled"), qa(A, status="queued", conclusion=None)],
     [cand(1, A)], "none|||"),
    ("no runs at all asks for a gate", [], [cand(1, A)], "dispatch|1|b1||"),
    ("a green draft is merged and flagged for promotion",
     [qa(A)], [cand(1, A, draft=True)], "merge|1|b1|%s|true" % A),

    # HEAD-OF-LINE. The queue drains oldest-first, so anything that stops the scan at the first
    # unmergeable PR blocks everything behind it. A red bot PR stays red until a human looks at it.
    ("a RED PR at the head does not block a green one behind it",
     [qa(A, conclusion="failure"), qa(B)], [cand(1, A), cand(2, B)],
     "merge|2|b2|%s|false" % B),
    ("an UNGATED PR at the head does not block a green one behind it",
     [qa(B)], [cand(1, A), cand(2, B)], "merge|2|b2|%s|false" % B),
    ("a RUNNING PR at the head does not block a green one behind it",
     [qa(A, status="queued", conclusion=None), qa(B)], [cand(1, A), cand(2, B)],
     "merge|2|b2|%s|false" % B),
    ("with a red head and an ungated tail, the tail gets the gate",
     [qa(A, conclusion="failure")], [cand(1, A), cand(2, B)], "dispatch|2|b2||"),
    ("only ONE gate is dispatched per tick, for the oldest ungated PR",
     [], [cand(1, A), cand(2, B), cand(3, C)], "dispatch|1|b1||"),
    ("the OLDEST green PR wins when several are green",
     [qa(A), qa(B)], [cand(1, A), cand(2, B)], "merge|1|b1|%s|false" % A),
    ("green beats dispatching, even when an older PR is ungated",
     [qa(B)], [cand(1, A), cand(2, B)], "merge|2|b2|%s|false" % B),
]

# (name, qa runs, candidates, substring that must appear in the FULL output)
NOTES = [
    ("a skipped red PR is reported as an error annotation",
     [qa(A, conclusion="failure")], [cand(7, A)], "::error::#7"),
    ("a red PR says it is being skipped, not that the run stopped",
     [qa(A, conclusion="failure")], [cand(7, A)], "Skipping it"),
]


def main():
    for name, prs, expect in ELIGIBILITY:
        check(name, run_pick(prs), expect, contains=True)
    for name, runs, cands, expect in DECISIONS:
        check(name, run_decide(runs, cands)[0], expect)
    for name, runs, cands, expect in NOTES:
        check(name, run_decide(runs, cands)[1], expect, contains=True)
    for name, prs, forbidden in NEVER:
        got = run_pick(prs)
        if forbidden in got:
            FAILED.append("%s\n      %r must NOT appear, but did" % (name, forbidden))

    total = len(ELIGIBILITY) + len(DECISIONS) + len(NOTES) + len(NEVER)
    if FAILED:
        print("pr-automerge logic: %d/%d passed, %d FAILED" % (total - len(FAILED), total,
                                                               len(FAILED)))
        for f in FAILED:
            print("  FAIL  %s" % f)
        return 1
    print("pr-automerge logic: %d/%d fixture cases passed" % (total, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
