# -*- coding: utf-8 -*-
"""Fixture tests for the decision logic inside .github/workflows/pr-automerge.yml.

WHY THIS IS IN THE GATE
-----------------------
`pr-automerge.yml` merges generated PRs to master unattended, and master auto-deploys to
Vercel. Its two Python blocks are therefore the last thing standing between a bot commit and
the live site, and a workflow cannot be unit-tested by running it — you only find out in
production. So this extracts both blocks from the YAML and runs them against fixtures.

The two questions worth protecting, because getting either wrong is silent rather than loud:

  1. WHO is eligible. Generated PRs come from two different authors: data/deck refreshes are
     `app/github-actions`, while the autonomous loop's PRs run under the OWNER's own account
     and are separated from hand-written ones only by a "Generated by [Claude Code]" marker.
     Widening this by accident auto-merges the owner's own work.

  2. Whether the gate really passed ON THE CURRENT HEAD. `cancelled` and `action_required`
     mean the gate never ran, and both are routine here (qa.yml sets cancel-in-progress; bot
     PRs land on action_required). Reading either as a verdict is the bug: as "green" it
     merges ungated code, as "red" it wedges the PR forever.

Deliberately does NOT import yaml — the gate's interpreter is not guaranteed to have it, and
the blocks are extracted from the raw text with the same indentation rules YAML would apply.
"""
import json
import os
import re
import subprocess
import sys
import tempfile
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
WF = os.path.join(REPO, ".github", "workflows", "pr-automerge.yml")


def _dedent_block(raw):
    """YAML `run: |` strips the block's common indentation before the shell sees it."""
    return textwrap.dedent(raw)


def extract():
    src = open(WF, encoding="utf-8").read()
    m = re.search(r"[ \t]*python3 - <<'PY'[^\n]*\n(.*?)\n[ \t]*PY\b", src, re.S)
    if not m:
        raise SystemExit("FAIL: could not find the eligibility block in %s" % WF)
    m2 = re.search(r'[ \t]*VERDICT=\$\(python3 -c "\n(.*?)\n[ \t]*"\)', src, re.S)
    if not m2:
        raise SystemExit("FAIL: could not find the gate-verdict block in %s" % WF)
    return _dedent_block(m.group(1)), _dedent_block(m2.group(1))


PICK_SRC, VERDICT_SRC = extract()
compile(PICK_SRC, "pick", "exec")
compile(VERDICT_SRC, "verdict", "exec")

TMP = tempfile.mkdtemp()


def run_pick(prs, owner="kaustavb2101"):
    p = os.path.join(TMP, "prs.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(prs, f)
    src = PICK_SRC.replace('"/tmp/prs.json"', json.dumps(p))
    env = dict(os.environ, OWNER=owner)
    return subprocess.run([sys.executable, "-c", src], capture_output=True,
                          text=True, env=env).stdout


def run_verdict(runs, sha):
    p = os.path.join(TMP, "runs.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(runs, f)
    src = VERDICT_SRC.replace("'/tmp/runs.json'", json.dumps(p))
    env = dict(os.environ, SHA=sha)
    r = subprocess.run([sys.executable, "-c", src], capture_output=True, text=True, env=env)
    return (r.stdout.strip() or r.stderr.strip())


def pr(n, login, body="", draft=False, state="CLEAN", created="2026-08-01",
       owner="kaustavb2101"):
    return {"number": n, "author": {"login": login}, "isDraft": draft,
            "headRefName": "b%d" % n, "headRefOid": "a" * 40, "body": body,
            "createdAt": created, "mergeable": "MERGEABLE", "mergeStateStatus": state,
            "headRepositoryOwner": {"login": owner}}


SHA = "a" * 40
FAILED = []


def check(name, got, expect, contains=False):
    good = (expect in got) if contains else (got == expect)
    if not good:
        FAILED.append("%s\n      expected %r, got %r" % (name, expect, got))
    return good


ELIGIBILITY = [
    ("actions bot is eligible", [pr(1, "github-actions")], "found=yes"),
    ("actions bot, bracketed login", [pr(1, "github-actions[bot]")], "found=yes"),
    ("hand-written owner PR is left alone",
     [pr(2, "kaustavb2101", body="just a fix")], "found=none"),
    ("loop PR carrying the Claude marker is eligible",
     [pr(3, "kaustavb2101", body="_Generated by [Claude Code](https://x)_")], "found=yes"),
    ("'Generated with' phrasing also matches",
     [pr(4, "kaustavb2101", body="Generated with [Claude Code](https://x)")], "found=yes"),
    ("null body does not crash the marker test",
     [{**pr(14, "kaustavb2101"), "body": None}], "found=none"),
    ("DIRTY is left to pr-autoresolve",
     [pr(5, "github-actions", state="DIRTY")], "found=none"),
    ("UNKNOWN mergeability waits for GitHub to finish computing",
     [pr(6, "github-actions", state="UNKNOWN")], "found=none"),
    ("a fork is never merged", [pr(7, "github-actions", owner="someone-else")], "found=none"),
    ("oldest eligible PR goes first",
     [pr(8, "github-actions", created="2026-08-09"),
      pr(9, "github-actions", created="2026-08-02")], "number=9"),
    # The deadlock guard: pr-autoresolve skips drafts and this job skips DIRTY, so a PR that is
    # both would be touched by neither and sit wedged forever. It must still be promoted.
    ("draft+DIRTY is promoted even though it cannot merge",
     [pr(10, "github-actions", draft=True, state="DIRTY")], "promote=10"),
    ("draft+DIRTY is still not merged",
     [pr(11, "github-actions", draft=True, state="DIRTY")], "found=none"),
    ("draft+CLEAN is both promoted and merged",
     [pr(12, "github-actions", draft=True, state="CLEAN")], "found=yes"),
    ("a hand-written draft is NOT promoted",
     [pr(13, "kaustavb2101", draft=True, body="mine")], "promote="),
]

VERDICTS = [
    ("success on this head is green",
     [{"headSha": SHA, "status": "completed", "conclusion": "success"}], "green"),
    ("success on a DIFFERENT head does not count (the stale-green trap)",
     [{"headSha": "b" * 40, "status": "completed", "conclusion": "success"}], "absent"),
    ("cancelled means the gate never ran, not that it failed",
     [{"headSha": SHA, "status": "completed", "conclusion": "cancelled"}], "absent"),
    ("action_required means the gate never ran either",
     [{"headSha": SHA, "status": "completed", "conclusion": "action_required"}], "absent"),
    ("a run still going is 'running'",
     [{"headSha": SHA, "status": "in_progress", "conclusion": None}], "running"),
    ("a real failure is red",
     [{"headSha": SHA, "status": "completed", "conclusion": "failure"}], "red:failure"),
    ("timed_out is red",
     [{"headSha": SHA, "status": "completed", "conclusion": "timed_out"}], "red:timed_out"),
    ("an earlier failure is superseded by a later success",
     [{"headSha": SHA, "status": "completed", "conclusion": "failure"},
      {"headSha": SHA, "status": "completed", "conclusion": "success"}], "green"),
    ("a queued run alongside a cancelled one is 'running' (never re-dispatch onto ourselves)",
     [{"headSha": SHA, "status": "completed", "conclusion": "cancelled"},
      {"headSha": SHA, "status": "queued", "conclusion": None}], "running"),
    ("no runs at all is absent", [], "absent"),
]


def main():
    for name, prs, expect in ELIGIBILITY:
        check(name, run_pick(prs), expect, contains=True)
    for name, runs, expect in VERDICTS:
        check(name, run_verdict(runs, SHA), expect)

    total = len(ELIGIBILITY) + len(VERDICTS)
    if FAILED:
        print("pr-automerge logic: %d/%d passed, %d FAILED" % (total - len(FAILED), total,
                                                               len(FAILED)))
        for f in FAILED:
            print("  FAIL  %s" % f)
        return 1
    print("pr-automerge logic: %d/%d fixture cases passed" % (total, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
