# -*- coding: utf-8 -*-
"""Merge the three Thai catalogue parts into docs/decks/mcom_th.json.

The catalogue is split across three python files rather than hand-edited as one JSON because JSON
cannot carry a comment, and a translation without a note on WHY a term was chosen (ราคาที่เกษตรกรขายได้
for farm gate, วัดจริง for MEASURED) decays the first time someone else touches it. The JSON is the
build artefact; the .py files are the source.

    python docs/decks/th/build_catalog.py            # write mcom_th.json
    python docs/decks/th/build_catalog.py --check    # verify it is already up to date

Validation, before anything is written:
  * a key may not appear in two parts with different translations
  * a template may not consume more placeholders than its key supplies — `"{} {}".format(one_arg)`
    raises at build time, and Deck._t() would silently fall back to English
  * every key must be Deck.tkey-normalised (no bare digits), or it can never match a live string
"""
import argparse
import json
import re
import string
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "mcom_th.json"
PARTS = ["labels", "headings", "prose", "misc"]

sys.path.insert(0, str(HERE.parent))
from deckkit import Deck                                            # noqa: E402  (path set above)

NUM = Deck._NUM            # one definition of "this is a number", shared with the builder
FMT = string.Formatter()


def slots(s):
    """How many positional arguments .format() would need to render s."""
    n = 0
    for _lit, field, _spec, _conv in FMT.parse(s):
        if field is None:
            continue
        if field == "":
            n += 1
        elif field.isdigit():
            n = max(n, int(field) + 1)
        else:
            raise ValueError(f"named placeholder {{{field}}} is not supported")
    return n


def load():
    sys.path.insert(0, str(HERE))
    merged, seen = {}, {}
    for part in PARTS:
        mod = __import__(part)
        for k, v in mod.STRINGS.items():
            if k in merged and merged[k] != v:
                raise SystemExit(f"conflict: {k[:70]!r} translated twice "
                                 f"({seen[k]} and {part}) with different text")
            merged[k], seen[k] = v, part
    return merged


def validate(cat):
    bad = []
    for k, v in cat.items():
        if not v.strip():
            bad.append(f"empty translation for {k[:70]!r}")
            continue
        if NUM.search(k):
            bad.append(f"key still carries a literal number (won't match): {k[:70]!r}")
        try:
            have, want = slots(k), slots(v)
        except ValueError as e:
            bad.append(f"{e} in {k[:60]!r}")
            continue
        if want > have:
            bad.append(f"template wants {want} placeholder(s), key supplies {have}: {k[:60]!r}")
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify mcom_th.json matches the sources")
    a = ap.parse_args()

    cat = load()
    bad = validate(cat)
    if bad:
        for b in bad:
            print("ERROR:", b)
        raise SystemExit(f"{len(bad)} catalogue problem(s)")

    payload = {
        "note": "Generated by docs/decks/th/build_catalog.py from labels.py + headings.py + "
                "prose.py — edit those, not this. Key = the English string with every number "
                "replaced by {}; value = the Thai, consuming the same numbers in the same order.",
        "strings": dict(sorted(cat.items())),
    }
    text = json.dumps(payload, ensure_ascii=False, indent=1) + "\n"

    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            raise SystemExit(f"{OUT.name} is out of date — re-run without --check")
        print(f"check OK — {len(cat)} strings")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} — {len(cat)} strings")


if __name__ == "__main__":
    main()
